Christophertorres/phs final tours spotlights styling
calblueprint/phs pull request #62
Opened 2024-05-05 10:45 UTC by christophertorres1

# ✨ New in this PR ✨

## One liner: what did you do? 🛠
Finalizing designs

## Coverage 🙆‍♀️

_use this section to break up your task into submodules and track progress, copy from Linear and mark what was completed_

- [X] Added/updated mobile and web designs for Hours & Location, Virtual Tours (all), and Wildlife Spotlights (all).
- [X] Made NavBar sticky.
- [X] Renamed all pages to latest names and switched from format \<exampleNamePage\> to \<example-name\>.

## How can the reviewer test your code? Where is this sprint located in the codebase? 👩‍💻
- Go through the pages mentioned above (and look at the URLs :] )

## REQUIRED: Link a short video demo of the feature you have added. 👩‍💻
Mobile:
https://github.com/calblueprint/phs/assets/99312117/00c746ed-d2e8-4938-869e-cfbf86a179d4

Web:
https://github.com/calblueprint/phs/assets/99312117/88f2abce-fe45-4448-a181-998d0dbd865b

## Any bugs you encountered or still having trouble with? 🐛
- For pages that access the 'window' object (e.g. checking for windowWidth) without waiting for the 'window' object first, opening/reloading that page on the browser will throw an error. I fixed this by initializing the width constant to some default value, and then setting thi

s value inside an 'if (window)' statement to ensure the window object is loaded before accessing it. @andreisito @jxmoose @miha-bhaskaran 

## Resources 📔

_REQUIREMENTS in this section: Link all relevant online resources and related PRs. Write down any new dependencies or packages and link to their documentation. If you ran into bugs, link any stack overflow or online resources that helped you unblock yourself_

## ❗IF this sprint was marked as FRONTEND on linear, cc Claire Wang

_REMEMBER: once PR is made, also request a PR review Sarah, CC'ing is NOT enough!_
🏚 cc: @sarahhpeng @andreisito @cluurie

2024-05-06 01:10 UTC, cluurie commented
HI CHRIS THIS IS AMAZINGGG just a few minor design notes 
**Virtual Tours Pages**
- check that the border radius for all button is 8px (all buttons on mobile should have 8px border radius)
- it looks like some text is still wonky --> make sure all the font styling and its default class thingy is correct (specifically i see that the line spacing for B3 body text is much larger, and font weights overall look thicker than it should
- check that end of tour page has more padding all around - ideally enough padding so that the footer doesnt show until u scroll
- also check the spacing between texts and buttons on the end of tour page
- "back to virtual tours" button has a smaller height 

**Spotlights Pages**
- check spacing between title and subtitle for the spotlight buttons
- line height of the subtext for spotlight buttons should be smaller (maybe a default text styling problem)
- for the related spotlights buttons, the subtext should be truncated at 2 lines (rn its at 1)
- the border radius for the "more in this spotlight" section under "bird attacks" + all the other spotlight pages look bigger than the main spotlight pages' (should be 8px!)

overall super incredibly dope ✨

2024-05-25 14:28 UTC, sarahhpeng approved these changes

2024-05-25 18:45 UTC, sarahhpeng requested changes
CHRIS THIS IS AMAZING!!!
couple of quick things for spotlights:
- for the "Found a Wild Animal" page, the text overflows on a web screen. would u be able to make it align with the image.
<img width="847" alt="Screenshot 2024-05-25 at 2 38 19 PM" src="https://github.com/calblueprint/phs/assets/137237272/f53500bc-1f12-4eb9-9a6f-58646d4a198a">
- would you be able to add the "Related Spotlights" section to all the spotlights. im looking at the figma file, and ik not all of the pages have that, and maybe that is a design choice. but tbh, none of the spotlights are really that related, so it seems sort of confusing to only have Related Spotlights for 1, and not all

2024-05-25 19:40 UTC, sarahhpeng approved these changes

2024-05-25 19:41 UTC, merged